In [17]:
import os
import re
import pandas as pd
pd.set_option('display.width', 1500)
pd.set_option('display.max_colwidth', 1500)
from nltk.corpus import stopwords

In [18]:
BASIC_PATH = os.getenv('PRJ_PATH', '/Users/msyang/tmp/natural-language-processing/notebooks/datasets')

In [19]:
cyberattack_df_02_03 = pd.read_csv(os.path.join(BASIC_PATH, 'datasets/twitter/cyberattack/cyberattack_2018_02_03.csv'))
cyberattack_df_03_04 = pd.read_csv(os.path.join(BASIC_PATH, 'datasets/twitter/cyberattack/cyberattack_2018_03_04.csv'))

cyberattack_df_04_05 = pd.read_csv(os.path.join(BASIC_PATH, 'datasets/twitter/cyberattack/cyberattack_2018_04_05.csv'))
cyberattack_df_05_06 = pd.read_csv(os.path.join(BASIC_PATH, 'datasets/twitter/cyberattack/cyberattack_2018_05_06.csv'))
cyberattack_df_06_07 = pd.read_csv(os.path.join(BASIC_PATH, 'datasets/twitter/cyberattack/cyberattack_2018_06_07.csv'))

cyberattack_df_07_08 = pd.read_csv(os.path.join(BASIC_PATH, 'datasets/twitter/cyberattack/cyberattack_2018_07_08.csv'))
cyberattack_df_08_09 = pd.read_csv(os.path.join(BASIC_PATH, 'datasets/twitter/cyberattack/cyberattack_2018_08_09.csv'))
cyberattack_df_09_10 = pd.read_csv(os.path.join(BASIC_PATH, 'datasets/twitter/cyberattack/cyberattack_2018_09_10.csv'))

print(cyberattack_df_02_03)

                time_stamp              id_str  retweet_count                                                                                                                                                                                                                                                                                                                                                                                                  text             user
0      2018-03-01 23:58:05  969361163078189056            0.0                                                                                                                                                                                                                   Cyberattack against German government 'ongoing,' causing considerable damage #CyberSecurity #CyberAttack #GermanGovernment #Network #RussianHacking #spying https://t.co/QcHi65VRJG      SwooseGoose
1      2018-03-01 23:55:06  969360409596776448            1.0                                                                                                                   When will retailers learn?  Tim Horton's now attacked -- not clear whether any credit card info stolen #timhorton #horton #cybersecurity #malware #Infosec #security #cyberattack #hacking #antivirus #ransomware #CyberCrime #Hacks #Hackers #CyberThreats https://t.co/LzcxWTqu6e    GraniteSecure
2      2018-03-01 23:40:07  969356641350144000            0.0                                                                                                                                                                                                                      15 steps to protect your company from a #cyberattack. #cybersecurity #ransomware #CryptoStopper https://t.co/0Z93iSqqw6 via @TheNextWeb via @scottgerber https://t.co/YkGlNLXG5p   WatchPointData
3      2018-03-01 23:39:39  969356524026920960            0.0                                                                                                                  @MarkTerrel @kentikinc I wonder if you can do some kind of side band validation that you can Rx packets at the UDP src ip you want to use, and then use UDP.  You'd want use some kind of expiring crypto-token to keep it stateless though. #memcached #cyberattack #cybersecurity.         mvachhar
4      2018-03-01 23:36:17  969355675049627648            0.0                                                                                                                                                                                                                                                                                                                                Is Your Business Vulnerable to a Cyberattack?  https://t.co/pjrOOVU0Oh   AnthemAdvisors
5      2018-03-01 23:36:01  969355610260234240            2.0                                                                                                                                                                                                                                            UDP is bad, mmm-kay? Some cool data on the recent #memcached #cyberattack from @kentikinc #cybersecurity   https://t.co/s0TBD9cHxe https://t.co/TQnvFXgEH9       MarkTerrel
6      2018-03-01 23:34:02  969355109506387969            1.0                                                                                                                             Five Things to Know about Cryptomining - CyberArk https://t.co/gIzvxUYDSj\n#Infosec #CyberSecurity #CyberAttack #Hack #Breach #Threat #DDoS #CyberWarfare  #Malware #Ransomware #Cyberwarning #Phishing #SpyWare\n#Tech #Technology #CryptoMining https://t.co/a9COxRRwlz         CioAmaro
7      2018-03-01 23:32:54  969354824578867200            0.0                                                                                                                                                                                                                                                                                       Is Your Business Vulnerable to a Cyberattack? https://t.co/gngmggQeyc #DigitalMarketing https://t.co/HR96u2vz1d  DigitalMPlanner
8      2018-03-01 23:30:31  969354225040920578            0.0                                                                                                                                           "I'm very confident the US government has a response if a major cyberattack were to occur," Lee said. "But what about a 30-minute power outage in DC? That's something that keeps me up at night [thinking about] how to respond."\nhttps://t.co/OxvmWDCE1j     sr2solutions
9      2018-03-01 23:19:21  969351413817061376            0.0                                                                                                                                                                                                                                         Brute force and dictionary attacks up 400 percent in 2017.\n#CyberSecurity #infosec #BruteForce #CyberAttack\nhttps://t.co/aDyRG8LoYV https://t.co/wx6EhiCxKh         GenieAll
10     2018-03-01 23:17:22  969350915198214146            1.0                                                                                                                                                                                                                                                          @burgermike @chrislhayes Trump is Protecting Putin NoSanctions, NoOrder for NSA 2Stop CyberAttack, No protection of 2018 election! Putin's B    carolyncares2
11     2018-03-01 23:15:03  969350331132989440            2.0                                                                                                                           Equifax finds ANOTHER 2.4 million Americans hit by breach\n#CyberSecurity #CyberAttack #CyberAware #infosecurity #dataprotection #dataprivacy #vulnerabilities #databreach #frauds #identityfraud #identity #identitytheft\nhttps://t.co/0isRLfzRyl https://t.co/BKkfAvzcYO           Shulab
12     2018-03-01 23:10:46  969349256283934720            0.0                                                                                                                                                                                                   RT SW_Integrity "Cyber #attack ongoing against German government network. The attack netted 17GB of data. Authorties worried it will be used to blackmail MPs. Read more:  https://t.co/81SnIR2TUl"   didier_botella
13     2018-03-01 23:10:08  969349094866079744            0.0                                                                                                                                             Anatomy of the Triton Malware Attack - CyberArk https://t.co/K9B2HQ3Vvc\n#Infosec #CyberSecurity #CyberAttack #Hack #Breach #Threat #DDoS #CyberWarfare  #Malware #Ransomware #Cyberwarning #Phishing #SpyWare\n#Tech #Technology https://t.co/DazThlkTsN         CioAmaro
14     2018-03-01 23:09:01  969348813512167424            2.0                                                                                                                                                   #Cybersecurity #poll #votenow; During 2018, will #DDoS attacks from #IoT #malware cause mass disruption to businesses that lack cloud contingency plans? Will we see some major businesses fail due to inadequate #cyberattack resilience?\nYes\nNo    RaefMeeuwisse
15     2018-03-01 23:06:06  969348081237024768            0.0                                                                                                                                                                                                                                     The $6bn Crime: 17 Million UK Consumers Hit Last Year. Globally, hackers stolen $172bn https://t.co/Ui9ZH8xYND\n\n#cyberattack #cybersecurity #UKsecurity #hacker  SecurEcomConslt
16     2018-03-01 23:06:06  969348079446044672            0.0                                                                                                                                                                                                                                     The $6bn Crime: 17 Million UK Consumers Hit Last Year. Globally, hackers stolen $172bn https://t.co/5g6vt6gUJT\n\n#cyberattack #cybersecurity #UKsecurity #hacker   IndikDashboard
17     2018-03-01 23:05:41  969347972961046529            0.0                                                                                                          NOTE; RUSSIA Hacking GERMANYS GOVT.&gt;BUT NOT necessarily THE RUSSIAN GOVT! PPL,consider that it might B R OWN CIA USING COZY BEAR AS ADMITED THEY DO 2 PRETEND THE"RE ANOTHER COUNTRY HACKING! AFTER ALL,THE KEY STONE FBI KOPS STILL SAY TRUMP COLLUSION 1.5 yrs\nhttps://t.co/huREtEX6QQ     reaganiteusa
18     2018-03-01 23:00:53  969346768612806656            1.0                                                                                                                                                                                                                     Cyber #attack ongoing against German government network. The attack netted 17GB of data. Authorties worried it will be used to blackmail MPs. Read more:  https://t.co/0dD6l5gXFV     SW_Integrity
19     2018-03-01 23:00:22  969346635884126209            0.0                                                                                                                                                                                  #HIPAA Compliance and #CitrixShareFile. https://t.co/8ItO3W2h5P @Net_Sec_News #healthsecurity #healthcare #cybersecurity #cyber #security #privacy #data #theft #cyberattack #dataprotection https://t.co/L7QTOatDWf     HIPAAJournal
20     2018-03-01 22:55:09  969345323574456320            0.0                                                                                                                                                                     A cyber attack disabling America's power grid would be catastrophic. New software developed @JohnsHopkins could help mitigate that risk: https://t.co/UIKNDl6aGP | #cyberattack #cybersecurity #powergrid https://t.co/S0O0l3T8sM            ESnet
21     2018-03-01 22:54:24  969345135099039744            0.0                                                                                                                                                                                       @ResistanceFever and EXXON drilling in Russia\nproviding &gt; monies for Putin to con't bullying NATO, EU, cyberattack USA,\nwage wars and pad Russian oligarchs to use dark money to effect our\nElections too     100Concerned
22     2018-03-01 22:50:47  969344223626502145            0.0                                                                                                                                                                                                                                         Cyberattack 'Ongoing' Against German Government Network | https://t.co/YHxKgSwGSS https://t.co/0TSFKAkoNJ via @SecurityWeek #security https://t.co/wzxqNv75J6       massilanzi
23     2018-03-01 22:48:19  969343604048171008            0.0                                                                                                                                                                   RT kaspersky: What could insider threats be costing your business? Download our new #ebook and learn how to protect your #employees and company from #cyberattack: https://t.co/FQTEs7xlH1 https://t.co/Mgj5n1dgSG #KSA #MiddleEast         afnamksa
24     2018-03-01 22:45:10  969342813178613762            0.0                                                                                                                                                                                                                                                                                         https://t.co/Hx5qXBqiKC : Cyber Attack Targets State Agencies [ransomware] https://t.co/1ITwkNOOFk #CDTTweets           CDTLLC
25     2018-03-01 22:45:00  969342769977315328            1.0                                                                                                                                                                                                  What could insider threats be costing your business? Download our new #ebook and learn how to protect your #employees and company from #cyberattack: https://t.co/hywt9MO6KV https://t.co/kDJD7qwPdA        kaspersky
26     2018-03-01 22:42:58  969342258079240192            1.0                                                                                                                                                                                                                                                                          Russian group hacked Germany‘s #Government #Germany #APT28 #CyberAttack #CyberSecurity #infosecnews  https://t.co/OY8cwvbStU     gh0st_Xpl0it
27     2018-03-01 22:41:18  969341840624406528            0.0                                                                                                                According to Germany’s #BfV intelligence:  #Snake - the group suspected of carrying out the #Bundeshack attack - first surfaced in 2005 and uses "a very complex, high quality software" - also goes by the name #Uroburos or #Turla.  https://t.co/3CM4lUx7pp https://t.co/gzqzgWlG04     rgoverstreet
28     2018-03-01 22:39:33  969341400281157633            0.0                                                                                                                         Ransomware next level -- listens to your microphone to hear your conversations -- this should be called badware! #cybersecurity #malware #Infosec #security #cyberattack #hacking #antivirus #ransomware #CyberCrime #Hacks #CyberThreats  #datatheft https://t.co/OpYWxQJJow    GraniteSecure
29     2018-03-01 22:35:03  969340263981346816            2.0                                                                                     CyberSecurity Inertia infiltrating the enterprise by CyberArk\nIs concern the very low changes in the enterprises, despite last year attacks\n#Infosec #CyberSecurity #CyberAttack #Breach #Threat #CyberWarfare  #Malware #Ransomware #Cyberwarning #Phishing #SpyWare #Tech #Technology https://t.co/FBFFCjrN8Z         CioAmaro
...                    ...                 ...            ...                                                                                                                                                                                                                                                                                                                                                                                                   ...              ...
21602  2018-02-01 01:24:15  958873598319509509            2.0  Great report on why voting machines are vulnerable to a cyberattack but since DHS never checked for malware in the 2016 election, no one can definitely say that tallies weren’t altered. #unhackthevote https://t.co/0aDqswu2Uf\nSpecific actions Congress and local election officials can quickly take to insulate voting technology from continued foreign interference. https://t.co/qiQlw28YcI       TanyasTwit
21603  2018-02-01 01:15:30  958871396888723457            0.0                                                                                                                                                                                                                                               New post from Kit Daniels: Was GOP Train Targeted by Cyberattack? https://t.co/2fd1hrw6Cz #prepyourselfnow #prepping #survival #homesteading #bugoutbag  PrepYourselfNow
21604  2018-02-01 01:10:44  958870195673665536            4.0                                                                                                                                                                                                                                                                                           News - EY announces offering to automate #cyberattack response workflow https://t.co/VFwyMIEBZs via @EYNews   MGremillion_EY
21605  2018-02-01 01:05:57  958868991715500032            0.0                                                                                                                                                                                                                                                             Since we're going old-school we should have flash-back Friday dress code this week and wear 70s themed clothing.\nhttps://t.co/wm2VZ7gpwh  MatthewAJohnson
21606  2018-02-01 01:04:01  958868505025220609            0.0                                                                                                                                                                                                                                                                                                         Jackpotting could leave thousand of ATMs at risk of cyberattack #tech https://t.co/8XgK6ClGvO          MdCplus
21607  2018-02-01 01:03:07  958868281317908480            0.0                                                                                                                                                                                                                                                            A CRIPPLING CYBERATTACK. A HEART-WRENCHING LOSS. WILL ONE MAN’S TH https://t.co/ZkKzI1nebj #Cybersecurity #Bitcoin https://t.co/dg6F3KYLXf  CyberToolsBooks
21608  2018-02-01 01:03:06  958868274166554624            0.0                                                                                                                                                                                                                                                            A CRIPPLING CYBERATTACK. A HEART-WRENCHING LOSS. WILL ONE MAN’S TH https://t.co/cHKCh9uFsb #Cybersecurity #Bitcoin https://t.co/vamUYbrOSk      CyberDomain
21609  2018-02-01 00:55:03  958866247894097920           34.0                                                                                                                                                                                                                                                      How can you recognize #Hackers ? \n\n#infosec #CyberSecurity #CyberAttack #SMM #cybercrime #disruption #fintech #Malware https://t.co/9mQ5DK2CpO      pradeeprao_
21610  2018-02-01 00:46:01  958863975072063488            0.0                                                                                                                                                                                                                                        CT, MRI machines face the greatest risk of cyberattack, researchers warn\n#Security #Healthcare #Vulnerability #CyberAttack\nhttps://t.co/WlMOLwmuJv by @zdnet        edleavens
21611  2018-02-01 00:41:12  958862762666594307            0.0                                                                                                                                                                                                                                                             Tips to use #penetration testing to protect your business from #cyberattack https://t.co/1FNQY9vEOJ #SMEs #biztip https://t.co/v8tcCgyKHK     IDTheftScout

In [22]:
cyberattack_df = pd.concat([cyberattack_df_02_03, cyberattack_df_03_04,
                            cyberattack_df_04_05, cyberattack_df_05_06, cyberattack_df_06_07, 
                            cyberattack_df_07_08, cyberattack_df_08_09, cyberattack_df_09_10])

In [23]:
def get_word_count(df, column_name):
    output = df[column_name].str.lower().str.split(expand=True).stack() \
                .value_counts() \
                .to_frame() \
                .reset_index() \
                .rename(columns={0: 'count', 'index': 'word'})
    output['ratio'] = output['count']/output['count'].sum()
    return output

In [24]:
word_count_df = get_word_count(cyberattack_df, 'text')
# Get most frequente hashtags
word_count_df = word_count_df[word_count_df['ratio'] > 0.0001]
word_count_df = word_count_df[word_count_df.word.str.contains('#')]
# hashtag stopwords
hashtag_stopwords = list(word_count_df.word.values)

In [25]:
from nltk.stem import WordNetLemmatizer, SnowballStemmer
import nltk
import spacy
nlp = spacy.load('en_core_web_sm')
stemmer = SnowballStemmer('english')

In [26]:
def replace_entities(input_text):
    doc = nlp(input_text)
    output = input_text
    for ent in doc.ents:
        if ent.label_ in ['PERSON', 'NORP', 'FAC', 'ORG', 'GPE', 'LOC']:
            output = output.replace( ent.text, ent.label_)
    return output

def lemmatize_stemming(text):
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))

def preprocess(raw_text, hashtag_stopwords):
    
    english_stopword = list(set(stopwords.words("english")))
    #hashtag_stopwords = [lemmatize_stemming(w.replace('#', '')) for w in hashtag_stopwords]
    stopword_list = english_stopword + hashtag_stopwords
    
    #exceptions for stopwords
    exceptions = ['down', 'under', 'against', 'from', 'more'] #attack
    for curr_e in exceptions:
        stopword_list.remove(curr_e)
    
    #remove urls
    raw_text = re.sub(r"http\S+", "", str(raw_text))
    
    #remove twitter specific words
    raw_text = re.sub('(RT)|(\n)', ' ', raw_text)
    raw_text = re.sub('(from @)|(via @)|(by @)', ' @', raw_text)
    raw_text = re.sub(r'[ ]{2,}', ' ', raw_text).strip()
    
    #remove usernames
    raw_text = re.sub(r'(?<=^|(?<=[^a-zA-Z0-9-_\.]))@([A-Za-z]+[A-Za-z0-9-_]+)', '', raw_text, flags=re.MULTILINE)
    
    # remove trailing hashtags
    raw_text = re.sub(r'( #\S+)*$', '', raw_text)
    
    #detect and replace entities
    #raw_text = replace_entities(raw_text)
    
    output = []
    for index, w in enumerate(raw_text.split()):
        preprocessed_word = lemmatize_stemming(re.sub(r'[^a-zA-Z\s]', "", w).lower())
        if w in ['__KEYWORD__', '__LTF__', '__RTK__', 'PERSON', 'NORP', 'FAC', 'ORG', 'GPE', 'LOC']:
            output.append(w)
        elif index == 0:
            output.append(preprocessed_word)
        elif preprocessed_word in stopword_list or len(preprocessed_word) > 10:
            continue
        else:
            output.append(lemmatize_stemming(re.sub(r'[^a-zA-Z\s]', "", w).lower()))
    output = " ".join(output)
    output = output if len(output.split()) >= 3 else pd.np.nan
    return output

In [27]:
df_ = cyberattack_df.text

In [28]:
df_ = df_.apply(lambda x: preprocess(x, hashtag_stopwords), 1)

In [29]:
df = df_.to_frame().reset_index()

In [30]:
df = df.dropna()
##df.dropna(how='any', inplace=True)

In [31]:
df = df.drop_duplicates(subset=['text'])
df.to_csv('processed_dataset_no_entities.csv')

In [348]:
#df = pd.read_csv('processed_dataset.csv')

In [32]:
positives = df[(~df.text.str.contains('(^do )|(^how )|(^will )|(^shall )'
                        '|(^what )|(^which )|(^when )|(^why )|(^who )|(^where )|(^while )|(^whose )'
                        '|(^be )|(^join )|(^attend )|(^find )|(\\bcours\\b)'
                        '|(top [0-9]+)|(\?)|(\\bstori\\b)(\\bclick\\b)'
                        '|(\\bfree webinar\\b)|(\\bsign now\\b)|(\\bregist\\b)|(\\bdownload\\b)|(\\blearn\\b)(\\bwatch\\b)', regex=True))
            &
           (df.text.str.contains('(\\bforc to\\b)|(\\bsay\\b)|(\\bwarn\\b)'
                                 '|(\\bpredict\\b)|(\\balert)|(\\bbreak\\b)|(\\bdamag\\b)'
                                 '|(\\bworri\\b)|(\\bhit\\b)|(\\btarget\\b)|(\\breport\\b)'
                                 '(\\bvulner\\b)|(\\bthreat\\b)|(\\battacks\\b)|(\\bongo\\b)'
                                 '(\\bhack\\b)|(\\binfect\\b)|(\\bshut down\\b)|(\\bdiscov\\b)|(\\btake down\\b)', regex=True))]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:11: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  # This is added back by InteractiveShellApp.init_path()

In [33]:
negatives = df[(df.text.str.contains('(^do )|(^how )|(^will )|(^shall )'
                        '|(^what )|(^which )|(^when )|(^why )|(^who )|(^where )|(^while )|(^whose )'
                        '|(^be )|(^join )|(^attend )|(^find )|(\\bcours\\b)'
                        '|(top [0-9]+)|(\?)|(\\bstori\\b)(\\bclick\\b)'
                        '|(\\bfree webinar\\b)|(\\bsign now\\b)|(\\bregist\\b)|(\\bdownload\\b)|(\\blearn\\b)(\\bwatch\\b)', regex=True))
   &
           (~df.text.str.contains('(\\bforc to\\b)|(\\bsay\\b)|(\\bwarn\\b)'
                                 '|(\\bpredict\\b)|(\\balert)|(\\bbreak\\b)|(\\bdamag\\b)'
                                 '|(\\bworri\\b)|(\\bhit\\b)|(\\btarget\\b)|(\\breport\\b)'
                                 '(\\bvulner\\b)|(\\bthreat\\b)|(\\battacks\\b)|(\\bongo\\b)'
                                 '(\\bhack\\b)|(\\binfect\\b)|(\\bshut down\\b)|(\\bdiscov\\b)|(\\btake down\\b)', regex=True))]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:11: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  # This is added back by InteractiveShellApp.init_path()

In [34]:
print('related tweets count:', positives.count())
print('un-related tweets count:',negatives.count())

related tweets count: index    17766
text     17766
dtype: int64
un-related tweets count: index    4927
text     4927
dtype: int64

In [35]:
pos_biased_words = ['attack', 'hit', 'target', 'infect', 'damag', 'vulner', 'take down', 'break down']
lite_notification_words = ['say', 'predict', 'alert', 'report']
heavy_notification_words = ['warn', 'worri']

drop_words =['us', 'russia', 'russian', 'singapor', 'uk', 
             'atlanta', 'putin', 'trump', 'ukrain', 'korea', 'america',
            'british', 'britain', 'usa', 'iran']
#drop_words = [lemmatize_stemming(w.replace('#', '')) for w in drop_words]

In [36]:
# Generalize keywords
# _RPK_ - replaced positive keyword
hashtag_keywords = ['#cyberattack', '#cybersecurity', '#infosec', '#malware', '#ransomware', '#security',
            '#technology', '#tech', '#phishing', '#cybercrime', '#hack', '#ddos', '#breach', '#threat',
            '#cyberwarfare', '#cyberwarning', '#databreach', '#hacking', '#spyware', '#hacker',
            '#hackers', '#cyber', '#cyberaware', '#privacy', '#dataprotection', '#vulnerability',
            '#cyberrisk', '#cyberthreat', '#itsecurity', '#informationsecurity', '#cybercriminals',
            '#pentest', '#mobilesecurity', '#mobilesecurity', '#iotsecurity', '#infosecurity', '#cyberdefence',
            '#notpetya', '#wannacry', '#networksecurity', '#exploit', '#ddosattack']
pos_keywords = [lemmatize_stemming(w.replace('#', '')) for w in hashtag_keywords]
keywords_regex = ''.join([('(\\b{0}\\b)|').format(w) for w in pos_keywords])
keywords_regex = keywords_regex[:len(keywords_regex)-1]

dropwords_regex = ''.join([('(\\b{0}\\b)|').format(w) for w in drop_words])
dropwords_regex = dropwords_regex[:len(dropwords_regex)-1]

biased_words_regex = ''.join([('(\\b{0}\\b)|').format(w) for w in pos_biased_words])
biased_words_regex = biased_words_regex[:len(biased_words_regex)-1]

lite_notification_words_regex = ''.join([('(\\b{0}\\b)|').format(w) for w in lite_notification_words])
lite_notification_words_regex = lite_notification_words_regex[:len(lite_notification_words_regex)-1]

heavy_notification_words_regex = ''.join([('(\\b{0}\\b)|').format(w) for w in lite_notification_words])
heavy_notification_words_regex = heavy_notification_words_regex[:len(heavy_notification_words_regex)-1]

In [37]:
positives['text'] = positives.text.str.replace(keywords_regex, '')
#positives['text'] = positives.text.str.replace(lite_notification_words_regex, '__NOTIFICATION_FORM__')
positives['text'] = positives.text.str.replace(dropwords_regex, '')

negatives['text'] = negatives.text.str.replace(keywords_regex, '')
negatives['text'] = negatives.text.str.replace(biased_words_regex, '')
#negatives['text'] = negatives.text.str.replace(lite_notification_words_regex, '__NOTIFICATION_FORM__')
negatives['text'] = negatives.text.str.replace(dropwords_regex, '')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [ ]:
#positives[positives.text.str.contains('shut',na=False)]

## Word count

In [38]:
negatives_count_df = get_word_count(negatives, 'text')
positives_count_df = get_word_count(positives, 'text')

In [39]:
negatives_count_df

            word  count     ratio
0            how   1352  0.027363
1           what    971  0.019652
2             be    880  0.017810
3           from    561  0.011354
4           busi    552  0.011172
5             do    491  0.009937
6        protect    466  0.009431
7           know    461  0.009330
8           data    387  0.007832
9           risk    339  0.006861
10          more    330  0.006679
11           amp    318  0.006436
12       compani    276  0.005586
13         learn    262  0.005303
14        prepar    247  0.004999
15        regist    245  0.004959
16          help    241  0.004878
17          when    234  0.004736
18       against    232  0.004695
19          find    220  0.004453
20           iot    212  0.004291
21          need    205  0.004149
22      download    202  0.004088
23           get    200  0.004048
24           use    196  0.003967
25      cyberwar    187  0.003785
26        botnet    182  0.003683
27         cours    178  0.003603
28          join    168  0.003400
29           new    165  0.003339
...          ...    ...       ...
5916      flight      1  0.000020
5917  austintech      1  0.000020
5918        fuze      1  0.000020
5919  dirtydevin      1  0.000020
5920     betanew      1  0.000020
5921         mid      1  0.000020
5922         fam      1  0.000020
5923       peasi      1  0.000020
5924  cruiseship      1  0.000020
5925     boarder      1  0.000020
5926     scaleup      1  0.000020
5927       elder      1  0.000020
5928   unsuspect      1  0.000020
5929       unwit      1  0.000020
5930       pwned      1  0.000020
5931          ar      1  0.000020
5932      crumbl      1  0.000020
5933    airtight      1  0.000020
5934  cloudspark      1  0.000020
5935   keylogegr      1  0.000020
5936         loy      1  0.000020
5937          iq      1  0.000020
5938         fls      1  0.000020
5939     defiant      1  0.000020
5940    kneejerk      1  0.000020
5941      goleta      1  0.000020
5942     wrongdo      1  0.000020
5943     happili      1  0.000020
5944        eena      1  0.000020
5945     backend      1  0.000020

[5946 rows x 3 columns]

## Machine Learning

In [40]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.externals import joblib

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
def get_dataset(positives, negatives):
    positives = positives.sample(frac=1)
    positives = positives[:5150]
    
    positives['label'] = 1
    negatives['label'] = 0
    dataset = pd.concat([positives, negatives])
    return dataset

def build_pipeline():
    pipeline = Pipeline([
        #, ngram_range=(1,3), use_idf=False, norm='l2'
        ('tfidf', TfidfVectorizer(lowercase=True, stop_words='english', use_idf=True)),
        #('svd', TruncatedSVD(algorithm='randomized', n_components=100)),
        # penalty='l2', alpha=0.0001,
        ('clf', SGDClassifier(loss='log', random_state=42))
    ])
    return pipeline


def prepare_data_for_training(data):
    data['text'] = data['text'].astype(str)
    X = data[['text']].apply(lambda x: ' '.join(x), axis=1)
    y = data['label'].values

    # Split the datasets between training and test set
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    print("Train size:", len(X_train), "Test size:", len(X_test))
    return X_train, X_test, y_train, y_test


def get_gridsearch_params():
    return {
           'tfidf__max_df': (0.5, 0.75, 1.0),
           'tfidf__max_features': (200, 400, 500),
           'tfidf__ngram_range': ((1, 2), (1,3)),
           'tfidf__norm': ('l1', 'l2'),
           'clf__penalty': ('l2', 'elasticnet'),
           'clf__alpha': (1e-2, 1e-3, 1e-4),
           'clf__max_iter': [5, 50, 100]
    }


def train_model(data, pipeline, parameters):
    X_train, y_train = data
    grid_search = GridSearchCV(pipeline, parameters, scoring='f1', verbose=1, cv=3, n_jobs=-1)
    grid_search.fit(X_train, y_train)

    print("Best parameters set:")
    best_parameters = grid_search.best_estimator_.get_params()
    for param_name in sorted(parameters.keys()):
        print("\t%s: %r" % (param_name, best_parameters[param_name]))
    return grid_search.best_estimator_


def evaluate_model(model, data):
    X_test, y_test = data
    target_names = ['0', '1']
    y_pred = model.predict(X_test)
    print("-" * 25)
    print(classification_report(y_test, y_pred, target_names=target_names))
    
def save_model(model, filename):
    joblib.dump(model, os.path.join(BASIC_PATH, "news_nlp/ml_models/", filename))

In [42]:
print("Loading dataset")
data = get_dataset(positives, negatives)
#data = pd.read_csv('cyberattack_processed_dataset.csv')
#data.to_csv('cyberattack_processed_dataset.csv')

print("Preparing datasets for training")
X_train, X_test, y_train, y_test = prepare_data_for_training(data)

print("Building pipeline")
pipeline = build_pipeline()

print("Training classification model")
model = train_model((X_train, y_train), pipeline, get_gridsearch_params())  #get_gridsearch_params() {} to get_gridsearch_params

print("Evaluating trained model")
evaluate_model(model, (X_test, y_test))

Loading dataset
Preparing datasets for training

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Train size: 8061 Test size: 2016
Building pipeline
Training classification model
Fitting 3 folds for each of 648 candidates, totalling 1944 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   11.7s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   46.6s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  5.4min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed:  7.6min
[Parallel(n_jobs=-1)]: Done 1944 out of 1944 | elapsed:  8.2min finished

Best parameters set:
	clf__alpha: 0.0001
	clf__max_iter: 100
	clf__penalty: 'elasticnet'
	tfidf__max_df: 0.5
	tfidf__max_features: 400
	tfidf__ngram_range: (1, 3)
	tfidf__norm: 'l2'
Evaluating trained model
-------------------------
              precision    recall  f1-score   support

           0       0.85      0.98      0.91       982
           1       0.98      0.83      0.90      1034

   micro avg       0.91      0.91      0.91      2016
   macro avg       0.91      0.91      0.91      2016
weighted avg       0.92      0.91      0.90      2016

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)

In [44]:
save_model(model, 'cyberattack_f92')

In [45]:
model = joblib.load(os.path.join(BASIC_PATH, "news_nlp", "ml_models", 'model_cyber_attack_last'))

FileNotFoundError: [Errno 2] No such file or directory: '/Users/msyang/tmp/natural-language-processing/notebooks/datasets/news_nlp/ml_models/model_cyber_attack_last'

## Analyzing results

In [46]:
# check if keyword exists
# if yes OK
# if not

#Is question szadi udali hashtagi, \n, url, mentions
# webinar vs course
# without action word NEGATIVE probability  > 0.9
# be accurate with threshold(no so much variance)

In [48]:
text = 'ibm was under attack on monday'
print(model.predict([preprocess(text, hashtag_stopwords)]))
mx = model.predict_proba([text])[0].max()
print(mx)

[1]
0.9993357676057363

## Label document

In [49]:
f = lambda x: model.predict([x])[0]
cyberattack_df_09_10['label'] = cyberattack_df_09_10.text.apply(f)
cyberattack_df_09_10.to_csv('results_09_10.csv')

In [50]:
cyberattack_df_09_10[cyberattack_df_09_10['label'] == 1][['text']].head(100)

                                                                                                                                                                                                                                                                                                                     text
2                                  March 2018, Russia caught cyber snooping in nuclear and energy systems. Obama worked a secret cyberattack rule that coordinated retaliation strikes; Donut Trump just reversed it. No more permission, no more coordination. Just him. https://t.co/W7rBYYjoBE https://t.co/DfbsKpiHjH
7                                                                                                                                                            The FBI and Homeland security are now investigating a ransomware attack on the port of San Diego\n#supplychainrisk #supplychaintech\nhttps://t.co/rxbZLcQIjx
8                                                                                                                                                            The FBI and Homeland security are now investigating a ransomware attack on the port of San Diego\n#supplychainrisk #supplychaintech\nhttps://t.co/28PQ515I0z
10                                                                          Excellent in-depth article: The day a mysterious systemic cyber-attack crippled Ukraine: https://t.co/FlI6AqWkcH\nRT @PatrickCoomans #CyberAttack #CyberWar #CyberSecurity #Infosec #CyberDefense https://t.co/vxC8WDov2o RT @CyberFuturecast
11                                                                                                                                                                      The port received a ransom note seeking payment in Bitcoin, but authorities will not say how much the attackers requested https://t.co/aee6cGnGm4
12                                                                                                                                                                              https://t.co/fucO687XAb Tesco Bank To Pay 16.4m Fine To Settle With FCA Over 2016 Cyberattack https://t.co/4DuIwUMEtg #globalsecuritynews
20                                                                                                                                                                               Tesco Bank hit with £16.4 million fine over cyber attack in 2016 #FCA #Tesco #bank #cyberattack: https://t.co/vcb26aRcxa via @NeowinFeed
24                                                                                                                                                        #TescoBank hit with £16.4 million fine over 2016 #CyberAttack that lead to £2.26 million #theft. #CyberSecurity https://t.co/xTG1uXUowQ https://t.co/moTaw2d4o3
30                                                                                                                                                                #Qatar is involved in the world’s biggest #cyberattack, went for 4 years and targeted 1400 #Americans and #Arabs \n#QatariLeaks https://t.co/8h3a3XzfHA
48                                                                                                                                                                                                                         Tesco Bank To Pay £16.4m Fine To Settle With FCA Over 2016 Cyberattack https://t.co/BsZnQrfytP
49                                                                                                                                                                                           Tesco Bank fined £16.4m over cyber-attack #CyberAttack #CyberSecurity #infosec #AI #Malware #Fintech https://t.co/1kHqxi9SLp
51                                                                                                                                  New Data Reveals Sharp Rise In Mobile Fraud Attacks\n\nhttps://t.co/s3hZVgMEqk \n\n#CyberSecurity #mobile #SecureCommunications #CyberAttack #smartphone #IoT https://t.co/KSBBI1mZQJ
54                                                                    New Xss on https://t.co/ZZ51pBUQ3b REF: xss-5bb2901fd4f95 https://t.co/OWvdt1115f #xss #infosec #hacking #hackers #security #yourXss #xssed #cybersecurity #infosec #tech #pentesting #pentest #DataSecurity #cybersecurity #bugbounty #cyberattack
58                                                                    New Xss on https://t.co/ZZ51pBUQ3b REF: xss-5bb28de381058 https://t.co/YonxMMxHi5 #xss #infosec #hacking #hackers #security #yourXss #xssed #cybersecurity #infosec #tech #pentesting #pentest #DataSecurity #cybersecurity #bugbounty #cyberattack
63                                                                                                                                                    Ho Ho Hold On A Minute… Cybersecurity experts warn holiday shoppers to be aware of “look-alike domains” that point them to malicious sites! https://t.co/VK4L1t20Wz
65                                                                                                                       44% of small businesses reported being the victim of a #cyberattack, with an average cost of approximately $9,000 per attack. #CyberAware #NCSAM https://t.co/Lv3fuWSPUK https://t.co/CPMEQK1sHv
66                                                                                                                  Combating foreign influences: the FBI's new initiatives to protect the US from online threats. https://t.co/QeNk0sRc1F \n#cybersecurity #FBI #espionage #cyberattack #threats https://t.co/m0fqP5j7M8
67                                                                                                                                                                                                 Tesco Bank To Pay £16.4m Fine To Settle With FCA Over 2016 Cyberattack https://t.co/C7tDpsXhrH https://t.co/mNa0GbujOa
75                                                                                                                               Researchers were able to attack a common speech recognition system using voice commands hidden in other audio recordings. #Alexa #CyberAttack #MachineLearning   https://t.co/VCQN3QOOLZ
76                                                                                                                                                                       Afternoon Coffee: New Trade Deal for North America Reached, Port of San Diego Hit by Cyberattack https://t.co/zEF2DX0usJ https://t.co/Eyy9TP7Gjs
77                                                                                                                                                                       Afternoon Coffee: New Trade Deal for North America Reached, Port of San Diego Hit by Cyberattack https://t.co/crIN1toznR https://t.co/zCcix8JNtl
78                                                                    New Xss on https://t.co/8dNJfjSNFi REF: xss-5bb2828ac0115 https://t.co/DaII8f9bkv #xss #infosec #hacking #hackers #security #yourXss #xssed #cybersecurity #infosec #tech #pentesting #pentest #DataSecurity #cybersecurity #bugbounty #cyberattack
80                                                                                                                                                      New post: Afternoon Coffee: New Trade Deal for North America Reached, Port of San Diego Hit by Cyberattack https://t.co/TffOqVyQ9v Sasajo/Adobe StockThe U.S. and
81    New Experts Corner! 🧐\n\nLearn About Cryptomining: The Latest Most Popular #Cyberattack\n\nBy @andynorton27000 of @lastlineinc\n\n"Criminal #cryptomining has indeed succeeded, which is why it has replaced #ransomware as the leading type of attack in 2018."\n\nhttps://t.co/hoBma3Y97w https://t.co/5bUarAx3Dz
90                  We're kicking off #CyberSecurity Awareness Month with a little quiz to think about if a #cyberattack were to affect our power. #CyberAwareness\n\nAccording to a @GridProtection survey earlier this year, what percentage of people are unprepared for an extended power outage?\n28%\n66%\n45%\n79%
91                                                                                                                 Port authorities around the globe should be on alert as the Port of San Diego suffered a #cyberattack, not too long after the Port of Barcelona. More via @campuscodi @ZDNet - https://t.co/psUpgdbkSo
95                                                                      New Xss on https://t.co/V6irWXyreW REF: xss-5bb27c167c9f9 https://t.co/ZrTE2Q0mAR #xss #infosec #hacking #hackers #security #yourXss #xssed #cybersecurity #infosec #tech #pentesting #pentest #DataSecurity #cybersecurity #website #cyberattack
96                      Port of San Diego suffered a #ransomware cyber attack via @Mar_Ex. As FBI &amp; DHS investigate the source, it affected administrative functions like park permits, public records requests, &amp; business services, but did not hurt seaport operations. #MaritimeNews\nhttps://t.co/mqnxwtHI8c
97                                                                      New Xss on https://t.co/vi7l3v7hnC REF: xss-5bb27ad38c353 https://t.co/3NHOyB50rh #xss #infosec #hacking #hackers #security #yourXss #xssed #cybersecurity #infosec #tech #pentesting #pentest #DataSecurity #cybersecurity #website #cyberattack
101                                                                                                                                                                       Tesco Bank hit with £16.4 million fine over cyber attack in 2016 https://t.co/ZOtCcDLLYh #FCA #Tesco #bank #cyberattack https://t.co/pbHrRdqvAt
..                                                                                                                                                                                                                                                                                                                    ...
246                                                                                                                                                                                                              #Tesco Bank Hit With Landmark £16M Fine For #Cyberattack https://t.co/R5gxqHDwun https://t.co/I4ca1lY7qP
255                                                                                                                                                                                                                                      Big banks notice rise in #cyberattack attempts: https://t.co/t6og2k3ZIp #banking
259                                                                                                                                                      6 out of 10 small businesses hit with a #cyberattack close their doors for good within 6 months. Read how you can avoid being a victim:\nhttps://t.co/b5c6bu1nMb
261                                                                                                                                        Cyber Attack, Don’t Panic! How to handle the situation should you become a victim\nhttps://t.co/XGs93wuVs5\n#CyberSecurity #GDPR #CyberAttack #FlockBN https://t.co/3pFtPTgsFv
268                                                                                                                                                   Ho Ho Hold On A Minute… Cybersecurity experts warn holiday shoppers to be aware of “look-alike domains” that point them to malicious sites! https://t.co/F8T2UVPOBe
269                                                                                                                                                                                Last year, close to a billion people were victims of a cyberattack or digital crime. Demand digital peace now. https://t.co/eTflnqQtl4
272  Threats of Phishing &amp; Ransomware \n#Infographics \n[ @CioAmaro ] #Infosec #CyberSecurity #CyberAttack #Hack #Breach #Threat #DDoS #Malware #Ransomware #Cyberwarning #Phishing #SpyWare\n#Tech #Technology\n@nancy_hiwatari @hack4lifemx @stacyannj @sanjaykatkar @jblefevre60 Cc: @Mike https://t.co/Xx5viOv1lk
273  Threats of Phishing &amp; Ransomware \n#Infographics \n[ @CioAmaro ] #Infosec #CyberSecurity #CyberAttack #Hack #Breach #Threat #DDoS #Malware #Ransomware #Cyberwarning #Phishing #SpyWare\n#Tech #Technology\n@nancy_hiwatari @hack4lifemx @stacyannj @sanjaykatkar @jblefevre60 Cc: @Mike https://t.co/M6ZJ5qBR1G
277                                                                                                                                              The UK is an easy target for cyber-attackers — we must reboot our defences\n\n#InfoSec #InfoSecurity #CyberSecurity #CyberAttack #UK #Target \n\nhttps://t.co/Q98BfO0sp5
278                                                                                                                                                                                                            Tesco Bank to pay £16.4m for 'failures' that led to 2016 cyberattack | TheINQUIRER https://t.co/205mNRLJ3B
283                                                                                                              Are you protecting your client data and keeping it secure? Tesco Bank fined £16.4m over cyber-attack https://t.co/Y8bHbVJc5U #BBCNews #CyberSecurity #GDPR #CyberAttack #FlockBN https://t.co/QJGDtzOHBE
284                                                                                                                                                                                                                                          Alert Logic report reveals new #cyberattack research https://t.co/jMwW3VpeBj
285                                                                                                                                                                                          Port of San Diego hit by #CyberAttack ransomware demand https://t.co/mmwuE9ObYj via @smartcitiesdive https://t.co/lPsAzFGvEQ
303                                                              "#Facebook is using your #2FA phone number to target #ads at you (ZDNet)" https://t.co/HbQxC8jn6l #InfoSec #Security #CyberSecurity #DataBreach #DataProtection #CyberAttack #CyberWar #Hacker #malware #Botnet #Ransomware #Technews #RT #advertisement
305                                                                                                                                           #Tesco #CyberAttack fines - 50% off original price!\nThis could’ve been avoided, but this did show a novel attack pattern for this #infosec breach\nhttps://t.co/U2Xgv9p3iQ
308                                                                                                                                Tesco Bank fined £16.4m over cyber-attack that put customers at risk\n#TescoBank #FinancialConductAuthority #Cyberattack #MarkSteward\nhttps://t.co/CQkeArOLBf https://t.co/5WXy3OdyxG
322                                                                                                                                                                                                                           UK watchdog considers fining Tesco Bank over cyberattack - Sky News https://t.co/L8n6c5xC9j
324                                                                                                                                                                                           Port of San Diego hit by cyberattack, ransomware demand - Smart Cities Dive https://t.co/5WSZzQ3m4h https://t.co/bYIKmnoILF
329                                                                                                                                      Press Association / The Guardian  UK’s Tesco Bank Agrees to Pay Fine of 16.4 Million Pounds to Settle Case With UK Regulator Related to 2016 Cyberattack https://t.co/FmagQPmHUS
334                                                                                           As much as we don’t want to admit it, #Cyberattacks are a way of life. Our Mike Frane has a few things to say on this topic. #CyberSecurityMonth18@Windstreambiz @MikeFrane https://t.co/uqie46Dm8E https://t.co/KdIthOCmBQ
335                                                                                                                                                                                           Port of San Diego hit by cyberattack, ransomware demand - Smart Cities Dive https://t.co/uFneFVyoSF https://t.co/jZu0EYvmXH
336                                                                                                                                      UK's Tesco Bank Agrees to Pay Fine of 16.4 Million Pounds to Settle Case With UK Regulator Related to 2016 Cyberattack @Guardian https://t.co/u1bDt6qmij https://t.co/lvKCH7DedB
342                                                                                                                                                                                                                Tesco Bank fined £16.4m over cyber attack https://t.co/T0Uqfhcfwv #CyberAttack https://t.co/D1nJm0y5OA
344                                        High-Profile Instagram Accounts Hacked For Ransom In A Campaign https://t.co/qwaKz5akw1\n#News [ @CioAmaro ] #Infosec #CyberSecurity #CyberAttack #Hack #Breach #Threat #DDoS #Malware #Ransomware #Cyberwarning #Phishing #SpyWare #Instagram #Hacked https://t.co/MOOITUxll7
355                                                                                                                                                                                                         .@TheFCA fines @TescoBankNews £16.4m over cyber attack\n\n#cyberattack #regulation\n\nhttps://t.co/FImhU0xDXJ
372                               "Tesco Bank fined £16.4m over cyber attack," via @ZDNet: https://t.co/qKLqYox99n #CyberSecurity #CyberAttack #CyberRisk #CyberThreats #CyberAware #infosec #DataSecurity #DataProtection #DataPrivacy #RiskManagement #Hackers #Hacking #DebitCards #IncidentResponse #Tesco #TescoBank
378                                                                                                                                                                           Tesco Bank fined £16.4m over cyber-attack.\n\nhttps://t.co/HdZG8fjBVu\n\n#Tesco #Banking #CyberSecurity #cybersecurite ##CyberAttack #Fined
382                                                                                                                                                                                  Tesco Bank fined £16.4m after cyber attack on accounts ? Daily Business https://t.co/rvou8JNTjG #CyberAttack https://t.co/N8Vk6IAxLT
389                                                                                                                                                                                                         Tesco Bank to pay £16.4m for 'failures' that led to 2016 #cyberattack: https://t.co/MAOWB82Uhy #cybersecurity
391                                                                                                                                                                                                                           BBC News - Tesco Bank fined £16.4m over #cyberattack https://t.co/bMZ9rjXaBK #cybersecurity

[100 rows x 1 columns]

## Filters

In [51]:
class CyberAttack_Filter:
    
    def __init__(self):
        keywords = ['#cyberattack', '#cybersecurity', '#infosec', '#malware', '#ransomware', '#security',
         '#technology', '#tech', '#phishing', '#cybercrime', '#hack', '#ddos', '#breach', '#threat', '#cyberwarfare',
         '#cyberwarning', '#databreach','#hacking', '#spyware', '#hacker', '#hackers',
         '#cyber', '#cyberaware', '#privacy', '#dataprotection','#vulnerability', '#cyberrisk','#cyberthreat']
        pos_keywords = [lemmatize_stemming(w.replace('#', '')) for w in keywords]
        keywords_regex = ''.join([('(\\b{0}\\b)|').format(w) for w in pos_keywords])
        self.keywords_regex = keywords_regex[:len(keywords_regex)-1]
        self.question_regex = '(^do )|(^how )|(^will )|(^shall )|(^what )|(^which )|(^when )|(^why )|(^who )|(^where )|(^while )|(^whose )|(^be )'
        self.stopwords_regex = '(\\bjoin\\b)|(\\battend\\b)|(\\bcours\\b)|(top [0-9]+)|(\?)|(\\bstori\\b)(\\bclick\\b)|(\\bfree webinar\\b)|(\\bsign now\\b)|(\\bregist\\b)|(\\bdownload\\b)|(\\blearn\\b)(\\bwatch\\b)'
    
    def has_keyword(self, processed_text):
        return len(re.findall(self.keywords_regex, processed_text)) > 0

    def has_question_form(self, orig_text, processed_text):
        return len(re.findall(self.question_regex, processed_text)) > 0 and orig_text.find('?') > -1
    
    def has_stopword(self, processed_text):
        return len(re.findall(self.stopwords_regex, processed_text)) > 0
    
    def has_min_context_length(self, orig_text):
        # remove urls
        orig_text = re.sub(r"http\S+", '', orig_text)
        # remove usernames
        orig_text = re.sub(r'(?<=^|(?<=[^a-zA-Z0-9-_\.]))@([A-Za-z]+[A-Za-z0-9-_]+)', '', orig_text, flags=re.MULTILINE)
        # remove hashtags
        orig_text = re.sub(r'#(\w+)', '', orig_text)
        # remove punctuation
        orig_text = re.sub(r'[^a-zA-Z\s]', '', orig_text)
        # remove 'nextline' and strip
        orig_text = orig_text.replace('\n', '').strip()
        return len(orig_text.split()) >= 3
    
    
    def filter_it(self, text):
        processed_text = " ".join([lemmatize_stemming(re.sub(r'[^a-zA-Z\s]', "", w)) for w in text.split()])
        
        if not self.has_min_context_length(text):
            return True
        
        if not self.has_keyword(processed_text):
            return True
        
        if self.has_question_form(text, processed_text) or self.has_stopword(processed_text):
            return True
        return False

In [52]:
text = 'cyberattack on russian computers'
cf = CyberAttack_Filter()
print(cf.filter_it(text))

False

## Tweet language claasifier

In [53]:
from langdetect import detect

ModuleNotFoundError: No module named 'langdetect'

In [ ]:
detect('地元ショップでも予約完了♡\n\n#NEWS #小山慶一郎 #手越祐也 #増田貴久 #加藤シゲアキ #OnlyYouぼくらのROMEOandJULIET \n#ゼロ一獲千金ゲーム #生きろ #希望〜yell〜 #エンドレス・サマー #NowPlaying #15thAnniversary')